# Default configuration for riscv-softmmu

CONFIG_SERIAL=y
CONFIG_VIRTIO_MMIO=y
include virtio.mak

CONFIG_CADENCE=y

# CONFIG_ATCUART100 depends on CONFIG_SERIAL
# CONFIG_ATCPIT100 depends on CONFIG_PTIMER
# CONFIG_ATFSDC010 depends on CONFIG_SD
CONFIG_PTIMER=y
CONFIG_SD=y
CONFIG_ATCUART100=y
CONFIG_ATCPIT100=y
CONFIG_ATFSDC010=y
CONFIG_ATFMAC100=y
